version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_myself_network
    volumes:
      - /home/rmmmm.9/nginx.conf:/etc/nginx/nginx.conf
      - gis_myself_static:/data/static/
      - gis_myself_media:/data/media/

  django:
    image: gis-myself:4
    networks:
      - gis_myself_network
    volumes:
      - gis_myself_static:/home/WebApplication_Myself/staticfiles/
      - gis_myself_media:/home/WebApplication_Myself/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_myself_network
    volumes:
      - gis_myself_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: password1
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1

networks:
  gis_myself_network:

volumes:
  gis_myself_static:
  gis_myself_media:
  gis_myself_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
